Get release info
X-R-G-B/Launcher pull request #1
Opened 2022-10-09 17:10 UTC by Saverio976

Pour avoir ton avis sur le code

2022-10-09 20:13 UTC, ThomasMarches requested changes

2022-10-09 20:13 UTC, ThomasMarches commented on src/people/people.rs
> +    }
```rust
for FirstName(name) in &query {
        println!("hello {name}!");
 }

2022-10-09 20:13 UTC, ThomasMarches commented on src/main.rs
> +use octocrab::Error;
Every use statement should be at the same place

2022-10-09 20:13 UTC, ThomasMarches commented on src/main.rs
> +const PRESSED_BUTTON: Color = Color::rgb(0.35, 0.75, 0.35);
I suggest you to create a const.rs file with every const variables if you know you will have lots

2022-10-09 21:41 UTC, skyf0l requested changes
I think, you need to create a `lib.rs` file with all features on the app and keep in the `main.rs` only the logic of the CLI. It can allow someone to reuse the backend of this tools and make the code more splitted and readable.

2022-10-09 21:41 UTC, skyf0l commented on src/main.rs
> +// use crate::people::people::*;
You can remove this dead code.

2022-10-09 21:41 UTC, skyf0l commented on src/main.rs
>  struct FirstName(String);
Theses structs are also in `people.rs` file, just import them.

2022-10-09 21:41 UTC, skyf0l commented on src/main.rs
> +/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Remove this useless lines, if you want to split a file in multiple parts, create multiples files.

2022-10-09 21:41 UTC, skyf0l commented on src/main.rs
> +use octocrab::Error;
```suggestion
use octocrab::{models::repos::Release, Error};
```

2022-10-09 21:41 UTC, skyf0l commented on src/main.rs
> +pub struct GithubReleaseResult(Task<Result<Release, Error>>);
Add `Debug` derive.

2022-10-09 21:41 UTC, skyf0l commented on src/main.rs
> +        let mut text = text_query.get_mut(children[0]).unwrap();
If you are sure this `unwrap` cannot fail, add a comment explaining why:

```rust
// PANIC: This should not fail because ...
```

2022-10-09 21:41 UTC, skyf0l commented on src/main.rs
> +/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
:eyes:

2022-10-09 21:41 UTC, skyf0l commented on src/people/people.rs
> +#![allow(clippy::too_many_arguments, clippy::type_complexity)]
This is not a good idea, if theses rules exist, it's for a reason...

2022-10-09 21:41 UTC, skyf0l commented on src/people.rs
> +pub mod people;
This is useless. If you want to create a `people` mod, just add this line in a `mod.rs` in the `people` folder.

2022-10-09 21:41 UTC, skyf0l commented on src/people/people.rs
> +pub struct FirstName(String);
Dont forget to add the `Debug` derive, it can help you a lot while debugging, you also can add `Eq`, `PartialEq`, `Clone` and `Copy` if it is possible.

2022-10-09 21:41 UTC, skyf0l commented on src/people/people.rs
> +}
I'm not sure you really need the `HelloPlugin` struct if its usage is just to create a static `HelloPlugin::build` function.
Therefore, this `build` function seem to be only related to the `App`, so move it in the `App` implementation such as `App:build_something`.

2022-10-10 09:20 UTC, KitetsuK commented on src/main.rs
> +                println!("salut");
👀

2022-10-11 18:19 UTC, KitetsuK commented on src/main.rs
> +const PRESSED_BUTTON: Color = Color::rgb(0.35, 0.75, 0.35);
The file cannot be named const.rs right ? Because we named it like that and it doesn t work

2022-10-11 18:22 UTC, ThomasMarches commented on src/main.rs
> +const PRESSED_BUTTON: Color = Color::rgb(0.35, 0.75, 0.35);
Was an exemple name, just to tell you to split your consts if you start to have a lot

2022-10-11 18:30 UTC, KitetsuK commented on src/main.rs
> +const PRESSED_BUTTON: Color = Color::rgb(0.35, 0.75, 0.35);
ok done

2022-10-14 19:58 UTC, KitetsuK commented
All files and method asked has been implemented you can re-check now if you want

2022-10-15 03:11 UTC, ThomasMarches requested changes
This is way better, just some little fixes left

2022-10-15 03:11 UTC, ThomasMarches commented on src/main.rs
> +        match *interaction {
This was not resolved

2022-10-15 03:11 UTC, ThomasMarches commented on src/main.rs
> +                    color: Color::rgb(0.9, 0.9, 0.9),
Why isnt this color isnt the const file ?

2022-10-15 03:11 UTC, ThomasMarches commented on src/main.rs
> +                    font: asset_server.load("fonts/FiraSans-Bold.ttf"),
Fonts should be inside const file

2022-10-15 03:11 UTC, ThomasMarches commented on src/main.rs
> +    dbg!(&releases);
Is this debug needed ? If not, you could directly return the value of
```rust
octo_inst
        .repos("X-R-G-B", "Artena")
        .releases()
        .get_latest()
        .await

2022-10-15 10:18 UTC, KitetsuK commented on src/main.rs
> +    dbg!(&releases);
No not really we should just print if the request succeed

2022-10-15 18:01 UTC, KitetsuK commented
I think we re good

2022-10-15 20:22 UTC, ThomasMarches approved these changes

2022-10-15 20:24 UTC, merged